<a href="https://colab.research.google.com/github/nguyenminhduc0233/NguyenMinhDuc_ML_2023/blob/main/Lab_6_20130233_NguyenMinhDuc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This lab is to deal with classification task using **Random Forests** and **Naïve Bayes** algorithms with/without **Feature Selection**. 

*   **Deadline: 23:59, 25/03/2023**



# Import libraries

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/ML_2023/Lab6'
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import svm
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import metrics
from prettytable import PrettyTable


Mounted at /content/gdrive
/content/gdrive/MyDrive/ML_2023/Lab6


#Task 1. 
Task 1. Compare the performance of selected classification algorithms including **Random forest**, **NaiveBayes**, and **SVM** with **mnist** dataset based on **accuracy, precision, recall, f1** measures according to **without using selection feature** and **using selection feature**.



In [ ]:
data_mnist = datasets.load_digits()
X = data_mnist.data
y = data_mnist.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 1)

In [ ]:
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
acc_random_forest = metrics.accuracy_score(y_test, y_pred,)
precision_random_forest = metrics.precision_score(y_test, y_pred, average='micro')
recall_random_forest = metrics.recall_score(y_test, y_pred, average='micro')
f1_random_forest = metrics.f1_score(y_test, y_pred, average='micro')

In [ ]:
clf = MultinomialNB()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
acc_naive_bayes = metrics.accuracy_score(y_test, y_pred)
precision_naive_bayes = metrics.precision_score(y_test, y_pred, average='micro')
recall_naive_bayes = metrics.recall_score(y_test, y_pred, average='micro')
f1_naive_bayes = metrics.f1_score(y_test, y_pred, average='micro')

In [ ]:
clf = svm.SVC(kernel='rbf')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
acc_svm = metrics.accuracy_score(y_test, y_pred)
precision_svm = metrics.precision_score(y_test, y_pred, average='micro')
recall_svm = metrics.recall_score(y_test, y_pred, average='micro')
f1_svm = metrics.f1_score(y_test, y_pred, average='micro')

In [ ]:
t = PrettyTable(['','acc','precision','recall','f1'])
t.add_row(['Random forest',acc_random_forest,precision_random_forest,recall_random_forest,f1_random_forest])
t.add_row(['NaiveBayes',acc_naive_bayes,precision_naive_bayes,recall_naive_bayes,f1_naive_bayes])
t.add_row(['SVM',acc_svm,precision_svm,recall_svm,f1_svm])
print(t)

+---------------+--------------------+--------------------+--------------------+--------------------+
|               |        acc         |     precision      |       recall       |         f1         |
+---------------+--------------------+--------------------+--------------------+--------------------+
| Random forest | 0.9796296296296296 | 0.9796296296296296 | 0.9796296296296296 | 0.9796296296296296 |
|   NaiveBayes  | 0.9018518518518519 | 0.9018518518518519 | 0.9018518518518519 | 0.9018518518518519 |
|      SVM      | 0.9851851851851852 | 0.9851851851851852 | 0.9851851851851852 | 0.9851851851851852 |
+---------------+--------------------+--------------------+--------------------+--------------------+


#Task 2. 
For given bank dataset (bank.csv) having the following attributes :
1.	**age** (numeric)
2.	**job** : type of job (categorical: 'admin.','blue-collar','entrepreneur','housemaid','management','retired','self-employed','services','student','technician','unemployed','unknown')
3.	**marital** : marital status (categorical: 'divorced','married','single','unknown'; note: 'divorced' means divorced or widowed)
4.	**education** (categorical: 'basic.4y','basic.6y','basic.9y','high.school','illiterate','professional.course','university.degree','unknown')
5.	**default**: has credit in default? (categorical: 'no','yes','unknown')
6.	**housing**: has housing loan? (categorical: 'no','yes','unknown')
7.	**loan**: has personal loan? (categorical: 'no','yes','unknown')
8.	**contact**: contact communication type (categorical: 'cellular','telephone')
9.	**month**: last contact month of year (categorical: 'jan', 'feb', 'mar', ..., 'nov', 'dec')
10.	**day_of_week**: last contact day of the week (categorical: 'mon','tue','wed','thu','fri')
11.	**duration**: last contact duration, in seconds (numeric). Important note: this attribute highly affects the output target (e.g., if duration=0 then y='no'). Yet, the duration is not known before a call is performed. Also, after the end of the call y is obviously known. Thus, this input should only be included for benchmark purposes and should be discarded if the intention is to have a realistic predictive model.
12.	**campaign**: number of contacts performed during this campaign and for this client (numeric, includes last contact)
13.	**pdays**: number of days that passed by after the client was last contacted from a previous campaign (numeric; 999 means client was not previously contacted)
14.	**previous**: number of contacts performed before this campaign and for this client (numeric)
15.	**poutcome**: outcome of the previous marketing campaign (categorical: 'failure','nonexistent','success')
Output variable (desired target):
16.	**y**. has the client subscribed a term deposit? (binary: 'yes','no')



#3.1. Apply StandardScaler() function to columns that contains numerical data ('age', 'balance', 'day', 'campaign', 'pdays', 'previous')

In [ ]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [ ]:
dataset = pd.read_csv("bank.csv", sep=",")
object= StandardScaler()
 
i_data = dataset[['age','balance','day','campaign','pdays','previous']]
response = dataset[['deposit']]

scale = object.fit_transform(i_data) 
print(scale)

[[ 1.49150488  0.25252514 -1.26574556 -0.55416834 -0.48118405 -0.36325984]
 [ 1.23967567 -0.4599736  -1.26574556 -0.55416834 -0.48118405 -0.36325984]
 [-0.0194704  -0.0801603  -1.26574556 -0.55416834 -0.48118405 -0.36325984]
 ...
 [-0.77495804 -0.46493443  0.39689074 -0.18678537 -0.48118405 -0.36325984]
 [ 0.14841574 -0.47392593 -0.90946635 -0.18678537  1.10957066  1.81833188]
 [-0.6070719  -0.47392593 -0.79070662 -0.55416834 -0.48118405 -0.36325984]]


#3.2. Apply Encode Categorical Value (OneHotEncoder) to transfrom categorical data to numerical data ('job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome')

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
# data = [['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']]

dataset["job"].unique()
dataset["marital"].unique()
dataset["education"].unique()
dataset["default"].unique()
dataset["housing"].unique()
dataset["loan"].unique()
dataset["contact"].unique()
dataset["month"].unique()
dataset["poutcome"].unique()


array(['unknown', 'other', 'failure', 'success'], dtype=object)

In [ ]:
ohe = OneHotEncoder()
feature_array = ohe.fit_transform(dataset[['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']]).toarray()
feature_label = ohe.categories_
print(feature_label)
np.array(feature_label).ravel()
pd.DataFrame(feature_array, columns = feature_label)

[array(['admin.', 'blue-collar', 'entrepreneur', 'housemaid', 'management',
       'retired', 'self-employed', 'services', 'student', 'technician',
       'unemployed', 'unknown'], dtype=object), array(['divorced', 'married', 'single'], dtype=object), array(['primary', 'secondary', 'tertiary', 'unknown'], dtype=object), array(['no', 'yes'], dtype=object), array(['no', 'yes'], dtype=object), array(['no', 'yes'], dtype=object), array(['cellular', 'telephone', 'unknown'], dtype=object), array(['apr', 'aug', 'dec', 'feb', 'jan', 'jul', 'jun', 'mar', 'may',
       'nov', 'oct', 'sep'], dtype=object), array(['failure', 'other', 'success', 'unknown'], dtype=object)]


<ipython-input-36-57934e304a4b>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(feature_label).ravel()


ValueError: ignored

#3.3. Apply **Decision tree, Random forest, kNN, NaïveBayes** to preproceed dataset in the previous steps. Then compare the obtained results using **accuracy, precision, recall, f1** measures.

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
X = dataset[['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome']]
y = dataset[['deposit']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 1)

In [ ]:
dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)
y_pred = dtree.predict(X_test)
acc_dtree = round((metrics.accuracy_score(y_test, y_pred)),4)
precision_dtree = round((metrics.precision_score(y_test, y_pred, average = 'macro')),4)
f1_dtree = round((metrics.f1_score(y_test, y_pred, average = 'macro')),4)
recall_dtree = round((metrics.recall_score(y_test, y_pred, average = 'macro')),4)

ValueError: ignored

In [ ]:
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
acc_random_forest = metrics.accuracy_score(y_test, y_pred,)
precision_random_forest = metrics.precision_score(y_test, y_pred, average='micro')
recall_random_forest = metrics.recall_score(y_test, y_pred, average='micro')
f1_random_forest = metrics.f1_score(y_test, y_pred, average='micro')

In [ ]:
for k in k_range:
  KNN = KNeighborsClassifier(n_neighbors = k)
  KNN.fit(X_train, y_train)
  y_pred = KNN.predict(X_test)
  accs.append(metrics.accuracy_score(y_test, y_pred))
  precision.append(metrics.precision_score(y_test, y_pred, average = 'micro'))
  recall.append(metrics.recall_score(y_test, y_pred, average = 'micro'))
  f1.append(metrics.f1_score(y_test, y_pred, average = 'micro'))
acc_knn = round(max(accs),4)
precision_knn = round(max(precision),4)
f1_knn = round(max(f1),4)
recall_knn = round(max(recall),4)

In [ ]:
clf = MultinomialNB()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
acc_naive_bayes = metrics.accuracy_score(y_test, y_pred)
precision_naive_bayes = metrics.precision_score(y_test, y_pred, average='micro')
recall_naive_bayes = metrics.recall_score(y_test, y_pred, average='micro')
f1_naive_bayes = metrics.f1_score(y_test, y_pred, average='micro')

In [ ]:
t = PrettyTable(['','acc','precision','recall','f1'])
t.add_row(['Decision tree',acc_dtree,precision_dtree,recall_dtree,f1_dtree])
t.add_row(['Random forest',acc_random_forest,precision_random_forest,recall_random_forest,f1_random_forest])
t.add_row(['NaiveBayes',acc_naive_bayes,precision_naive_bayes,recall_naive_bayes,f1_naive_bayes])
t.add_row(['KNN',acc_knn,precision_knn,recall_knn,f1_knn])
print(t)

#3.4. Using selection feature to above dataset, then compare the classification results with those in Task 2.3. 

In [ ]:
#code

#Task 4. 
For a given dataset in the Lab #5 (**credit card dataset**), perform feature selection and thencompare the performance of selected classification algorithms (Decision Tree, kNN, Logistic Regression, SVM, Random Forest and NaiveBayes) based on accuracy, precision, recall, f1 measures.


In [ ]:
# code

#Finally,
Save a copy in your Github. Remember renaming the notebook.